import type { Lang } from "@/app/types";
import type { HistoricalOutlook as Outlook } from "@/lib/historicalOutlook";

export function HistoricalOutlook({ outlook, loading, lang }: { outlook: Outlook | null; loading: boolean; lang: Lang }) {
  const pct = (value: number | null | undefined) => value == null ? "—" : `${value >= 0 ? "+" : ""}${(value * 100).toFixed(1)}%`;
  const scenario = (label: string, value: { low: number; median: number; high: number; positiveRate: number } | null) => <div className="rounded-xl bg-violet-50 p-2.5 dark:bg-violet-950/30"><p className="text-[10px] font-semibold uppercase tracking-wide text-violet-700 dark:text-violet-300">{label}</p><p className="mt-1 text-sm font-semibold">{value ? `${pct(value.low)} a ${pct(value.high)}` : "—"}</p>{value && <p className="mt-0.5 text-[11px] text-gray-500 dark:text-gray-400">{lang === "es" ? `Mediana ${pct(value.median)} · ${Math.round(value.positiveRate * 100)}% positivos` : `Median ${pct(value.median)} · ${Math.round(value.positiveRate * 100)}% positive`}</p>}</div>;
  return <div className="bg-white border rounded-2xl p-4 dark:bg-neutral-900 dark:border-neutral-700"><div className="flex items-baseline justify-between gap-2"><div><div className="text-xs font-semibold uppercase tracking-wide text-gray-500">{lang === "es" ? "Outlook histórico" : "Historical outlook"}</div><p className="mt-1 text-xs text-gray-500">{lang === "es" ? "Rangos observados en la historia; no es una predicción garantizada." : "Ranges observed in history; not a guaranteed prediction."}</p></div>{outlook && <span className="text-[10px] text-gray-400">{outlook.observations} {lang === "es" ? "sesiones" : "sessions"}</span>}</div>{loading ? <div className="mt-3 h-20 animate-pulse rounded-xl bg-gray-100 dark:bg-neutral-800" /> : !outlook ? <p className="mt-3 text-xs text-gray-400">{lang === "es" ? "Historial insuficiente para calcular el outlook." : "Insufficient history to calculate the outlook."}</p> : <><div className="mt-3 grid grid-cols-2 gap-2">{scenario(lang === "es" ? "Rango histórico 1 mes" : "1-month historical range", outlook.oneMonth)}{scenario(lang === "es" ? "Rango histórico 3 meses" : "3-month historical range", outlook.threeMonths)}</div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><Stat label={lang === "es" ? "Volatilidad anual" : "Annual volatility"} value={pct(outlook.volatility)} /><Stat label="Beta SPY" value={outlook.beta?.toFixed(2) ?? "—"} /><Stat label={lang === "es" ? "Peor caída" : "Max drawdown"} value={pct(outlook.maxDrawdown)} /></div></>}</div>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] text-gray-500">{label}</p><p className="font-semibold">{value}</p></div>; }
