-- Migration 008: daily market diary insights
-- Mirrors the production table shape and keeps writes service-role only.

CREATE TABLE IF NOT EXISTS daily_insights (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date               DATE NOT NULL,
  lang               TEXT NOT NULL CHECK (lang IN ('en', 'es')),
  sentiment_score    NUMERIC,
  sentiment_label    TEXT,
  sentiment_summary  TEXT,
  top_news           JSONB,
  aggregate_scores   JSONB,
  notable_events     TEXT,
  ai_insight         TEXT,
  whale_activity     JSONB,
  reviewer_feedback  TEXT,
  raw_data           JSONB,
  version            TEXT,
  created_at         TIMESTAMPTZ DEFAULT now(),
  UNIQUE (date, lang)
);

-- Upgrade a table that existed before this migration. Existing rows were
-- written after the Spanish pass, so their retained language is Spanish.
ALTER TABLE daily_insights ADD COLUMN IF NOT EXISTS lang TEXT;
UPDATE daily_insights SET lang = 'es' WHERE lang IS NULL;
ALTER TABLE daily_insights ALTER COLUMN lang SET NOT NULL;

DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  SELECT conname INTO constraint_name
  FROM pg_constraint
  WHERE conrelid = 'daily_insights'::regclass
    AND contype = 'u'
    AND conkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid = 'daily_insights'::regclass AND attname = 'date')];

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE daily_insights DROP CONSTRAINT %I', constraint_name);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'daily_insights'::regclass
      AND contype = 'u'
      AND conkey = ARRAY[
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'daily_insights'::regclass AND attname = 'date'),
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'daily_insights'::regclass AND attname = 'lang')
      ]
  ) THEN
    ALTER TABLE daily_insights ADD CONSTRAINT daily_insights_date_lang_key UNIQUE (date, lang);
  END IF;
END $$;

ALTER TABLE daily_insights ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'daily_insights'
      AND policyname = 'Public read daily_insights'
  ) THEN
    CREATE POLICY "Public read daily_insights"
      ON daily_insights FOR SELECT
      USING (true);
  END IF;
END $$;

-- Pipeline writes use the service role key, which bypasses RLS. Do not grant
-- public insert/update access here.
